//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
[System.Serializable]
public class BulletEmitter : MonoBehaviour
{
	List<BulletPattern> bPatterns;
	public List<String> Patterns;
    public bool m_autoFire = false;

	public GameObject m_customBulletType;

	public Vector2 Target;
	public BulletEmitter ()
	{
	}

	public void Awake() {
		Refresh();
	}

	public void Refresh() {
		bPatterns = new List<BulletPattern>();
		foreach (var p in Patterns) {
			var args = p.Split(':');
			int count = 1;
			float angle = 0;
			switch (args[0]) {
				case "line":
					count = 1;
					angle = 0;
					if (args.Length > 1) {
						count = Convert.ToInt32(args[1]);
					}
					if (args.Length > 2) {
						angle = float.Parse(args[2]);
					}
					if (m_customBulletType != null)
					{
						bPatterns.Add(new BulletLinePattern(this, count, angle, Constants.NORMAL_BULLET_PERIOD, Constants.NORMAL_BULLET_SPEED, m_customBulletType));
					}
					else
					{
						bPatterns.Add(new BulletLinePattern(this, count, angle, Constants.NORMAL_BULLET_PERIOD, Constants.NORMAL_BULLET_SPEED));
					}
					break;
				case "sine":
					break;
				case "parabola":
					count = 1;
					angle = 0;
					if (args.Length > 1) {
						count = Convert.ToInt32(args[1]);
					}
					if (args.Length > 2) {
						angle = float.Parse(args[2]);
					}
					if (m_customBulletType != null)
					{
						bPatterns.Add(new BulletParabolaPattern(this, count, angle, Constants.NORMAL_BULLET_PERIOD, Constants.NORMAL_BULLET_SPEED, m_customBulletType));
					}
					else
					{
						bPatterns.Add(new BulletParabolaPattern(this, count, angle, Constants.NORMAL_BULLET_PERIOD, Constants.NORMAL_BULLET_SPEED));
					}
					break;
				default:
					break;
			}
		}
	}

	public void FixedUpdate() {
		if (m_autoFire)
        {
            foreach (var p in bPatterns)
            {
                p.Step(this.gameObject.transform.position.GetVector2(), Target);
            }
        }
	}

    public void ToggleAutoFire()
    {
        m_autoFire = !m_autoFire;
    }
}

