//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class BulletManager
{
	public List<GameObject> m_BulletPool = new List<GameObject> ();
	private static BulletManager inst = null;

	public static BulletManager Inst {
		get {
			if (inst == null) {
				inst = new BulletManager();
			}
			return inst;
		}
	}

	private BulletManager ()
	{
	}

	public GameObject GetBullet() {
		if (m_BulletPool.Count == 0) {
			for (int i = 0; i < 10; ++i) {
				GameObject objj = UnityEngine.Object.Instantiate(Resources.Load("Bullet")) as GameObject;
				objj.SetActive(false);
                m_BulletPool.Add(objj);
			}
		}
		GameObject obj2 = m_BulletPool.First();
		obj2.SetActive(true);
		m_BulletPool.RemoveAt(0);
		return obj2;
	}

	public void FreeBullet(GameObject bullet) {
		bullet.SetActive(false);
		m_BulletPool.Add(bullet);
	}
}

