//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Bullet : MonoBehaviour
{
	public float m_currentLife;
	public int m_dmg;
	public Bullet ()
	{
	}
		
	public void Free() {
		if (this.gameObject != null) {
			BulletManager.Inst.FreeBullet(this.gameObject);
		}
	}

	public void Update() {
		m_currentLife -= Time.deltaTime;
		if (m_currentLife < 0) {
			Free();
		}
	}
}

